ontologyTitleURI=https://eriktuck.github.io/results-chain-ontology/
ontologyName=Conservation Results Chain Ontology
ontologyTitle=Conservation Results Chain Ontology
ontologyPrefix=rc
ontologyNamespaceURI=https://eriktuck.github.io/results-chain-ontology/
ontologyRevisionNumber=1.0.0
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=Creative Commons Attribution 4.0 International (CC-BY 4.0)
authors=Erik Anderson (https://orcid.org/0009-0002-7070-7178)
pathToAbstract=sections/abstract-en.html
pathToIntro=sections/introduction-en.html